"""Generate modoverrides.lua from Python data and write it atomically."""

from __future__ import annotations

import math
import os
import tempfile
from pathlib import Path
from typing import Any

from app.models import OverrideEntry

LUA_KEYWORDS = frozenset(
    "and break do else elseif end false for function goto if in local nil not "
    "or repeat return then true until while".split()
)

_STRING_ESCAPES = {
    "\\": "\\\\",
    '"': '\\"',
    "\n": "\\n",
    "\r": "\\r",
    "\t": "\\t",
}


def lua_string(value: str) -> str:
    """Quote a Python string as a Lua string literal."""
    out: list[str] = ['"']
    for ch in value:
        if ch in _STRING_ESCAPES:
            out.append(_STRING_ESCAPES[ch])
        elif ord(ch) < 32:
            # Zero-padded decimal escape so a following digit can't extend it.
            out.append(f"\\{ord(ch):03d}")
        else:
            out.append(ch)
    out.append('"')
    return "".join(out)


def lua_key(key: str) -> str:
    """Render a table key: bare when it is a valid Lua identifier."""
    if key.isidentifier() and not key[0].isdigit() and key not in LUA_KEYWORDS:
        # str.isidentifier allows non-ASCII letters, which Lua does not; keep
        # it simple and require ASCII.
        if key.isascii():
            return key
    return f"[{lua_string(key)}]"


def lua_value(value: Any) -> str:
    """Render a Python value as a Lua literal.

    Scalars map 1:1 (None -> nil); dicts/lists are rendered as inline tables
    so values we merely *preserve* from an existing file survive a rewrite.
    """
    if value is None:
        return "nil"
    if isinstance(value, bool):  # bool check must precede int (bool <: int)
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"cannot represent non-finite number in Lua: {value!r}")
        return repr(value)
    if isinstance(value, str):
        return lua_string(value)
    if isinstance(value, dict):
        inner = ", ".join(
            f"{lua_key(str(k))} = {lua_value(v)}" for k, v in value.items()
        )
        return "{ " + inner + " }"
    if isinstance(value, (list, tuple)):
        return "{ " + ", ".join(lua_value(v) for v in value) + " }"
    raise TypeError(f"cannot represent value of type {type(value).__name__} in Lua")


def render_overrides(entries: dict[str, OverrideEntry]) -> str:
    """Render a complete, stable, human-readable modoverrides.lua."""
    # No timestamp here on purpose: identical settings must produce an
    # identical file, so backup diffs only show real changes.
    lines = [
        "-- Generated by dst-mod-manager.",
        "-- Manual edits will be overwritten the next time you save from the web UI.",
        "return {",
    ]
    for key in sorted(entries):
        entry = entries[key]
        lines.append(f"    [{lua_string(key)}] = {{")
        lines.append(f"        enabled = {lua_value(entry.enabled)},")
        lines.append("        configuration_options = {")
        for opt_name in sorted(entry.configuration_options, key=str.lower):
            opt_value = entry.configuration_options[opt_name]
            if opt_value is None:
                # In a Lua table `k = nil` is identical to omitting the key —
                # it disappears on the next parse anyway, so writing it would
                # only produce phantom file changes between saves.
                continue
            lines.append(f"            {lua_key(opt_name)} = {lua_value(opt_value)},")
        lines.append("        },")
        lines.append("    },")
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_file_atomic(path: Path, content: str) -> None:
    """Write via temp file + rename so a crash can't leave a torn file."""
    if not path.parent.is_dir():
        raise FileNotFoundError(
            f"target directory does not exist: {path.parent} "
            f"(is the shard configured correctly?)"
        )
    fd, tmp_name = tempfile.mkstemp(
        dir=path.parent, prefix=f".{path.name}.", suffix=".tmp"
    )
    tmp_path = Path(tmp_name)
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(tmp_path, path)
    except BaseException:
        tmp_path.unlink(missing_ok=True)
        raise


def write_overrides(path: Path, entries: dict[str, OverrideEntry]) -> None:
    write_file_atomic(path, render_overrides(entries))
