-- Generated by dst-mod-manager.
-- Manual edits will be overwritten the next time you save from the web UI.
return {
    ["workshop-123456789"] = {
        enabled = true,
        configuration_options = {
            CHEST_SIZE = 9,
            OWNER_TAG = "none",
        },
    },
    ["workshop-378160973"] = {
        enabled = true,
        configuration_options = {
            ENABLEPINGS = true,
            FIREOPTIONS = 2,
            OVERRIDEMODE = false,
            SHAREMINIMAPPROGRESS = true,
            SHOWFIREICONS = true,
            SHOWPLAYERICONS = true,
            SHOWPLAYERSOPTIONS = 2,
        },
    },
    ["workshop-661253977"] = {
        enabled = true,
        configuration_options = {
            amudiao = true,
            baodiao = 1,
            kong = 0,
            nillots = 0,
            rendiao = 2,
            zbdiao = true,
        },
    },
    ["workshop-999999999"] = {
        enabled = false,
        configuration_options = {
        },
    },
}
